### PR TITLE
OSGi support

### PR DESCRIPTION
**Pull request by saksmt**

### CODE REVIEW

**Comment by jhalterman** [comment]
The classloader change looks good.

For the manifest, how about generating the manifest via the maven bundle plugin? That way any code changes in the future will be automatically picked up.

**Comment by saksmt** [comment]
@jhalterman,
OK, I'll add it in a moment. I've just thought that new dependencies isn't good decision.

**Comment by jhalterman** [comment]
The bundle plugin is cool with me since it's just a build dependency.

**Comment by jhalterman** [comment]
Oh, one more thing I noticed. We need to keep the original  `Connections.create(ConnectionOptions, Config)` method for backwards compatibility. It can just call the new `Connections.create(ConnectionOptions, Config, ClassLoader)` method.

**Comment by saksmt** [comment]
Forgot about this overload.

**Comment by jhalterman** [comment]
Thanks!

**Comment by jhalterman** [comment]
0.5.3 is released with this change. It should be in central in an hour or so.

**Comment by saksmt** [comment]
Thanks for quick approval! Now need to remove hack from my production code :smile:

**Pull request merged**
