### PR TITLE
Add support for NIO that added in rabbit client 4.x

### PR DESCRIPTION
**Pull request by igreenfield**

### CODE REVIEW

**Comment by michaelklishin** [comment]
@jhalterman this looks like a useful and low risk improvement. 👍 from team RabbitMQ.

**Comment by jhalterman** [comment]
@igreenfield Thanks a lot for this. Before I merge, are there any test cases that make sense to include with these commits?

**Comment by igreenfield** [comment]
@jhalterman I don't see any test needed.

**Comment by jhalterman** [comment]
Thanks again for this!

**Comment by igreenfield** [comment]
@jhalterman When you will release version with this?

**Comment by jhalterman** [comment]
Just released 0.5.4 that includes this. It should be in central shortly...

**Pull request merged**
